# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: shadesi
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: meetapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: auth-server

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  timeout: 30 # optional, in seconds
  environment:
    CLIENT_ID: ${file(./config/config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(./config/config.json):CLIENT_SECRET}
    CALENDAR_ID: ${file(./config/config.json):CALENDAR_ID}

functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
